# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_img',
            field=models.ImageField(default='NULL', upload_to='products'),
        ),
    ]
